--PARKING1
--PARKING_ID  	DESCRIPTION  	FIXED_AMOUNT  	NAME_UID  	PRICINGPOLICY
INSERT INTO PARKING VALUES (1, 'Parking1 POC', 0, 'PARKING1', 'HOUR');
--Parking Slots for PARKING1
--PARKINGSLOT_ID  	ENGINETYPE  	FLOOR  	OCCUPIED  	POSITION  	VEHICLETYPE  	PARKING_ID 
INSERT INTO PARKINGSLOT VALUES (1 , 'GASOLINE' , 1 , 0 , 101, 'CAR' , 1);
INSERT INTO PARKINGSLOT VALUES (2 , 'GASOLINE' , 1 , 0 , 102, 'CAR' , 1);
INSERT INTO PARKINGSLOT VALUES (3 , 'E20KW' , 1 , 0 , 103, 'CAR' , 1);
INSERT INTO PARKINGSLOT VALUES (4 , 'E20KW' , 1 , 0 , 104, 'CAR' , 1);
INSERT INTO PARKINGSLOT VALUES (5 , 'E50KW' , 1 , 0 , 105, 'CAR' , 1);

--BILL
--PARKINGSLOT_ID  	ACTIVE  	AMOUNT  	CURRENCY  	PAYED  
INSERT INTO BILL VALUES ( 1 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 2 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 3 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 4 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 5 , 0 , 0 , 'EUR' , 1);


--PARKING2
INSERT INTO PARKING VALUES (2, 'Parking2 POC', 0, 'PARKING2', 'FEE_HOUR');
--Parking Slots
INSERT INTO PARKINGSLOT VALUES (6 , 'GASOLINE' , 1 , 0 , 101, 'CAR' , 2);
INSERT INTO PARKINGSLOT VALUES (7 , 'GASOLINE' , 1 , 0 , 102, 'CAR' , 2);
INSERT INTO PARKINGSLOT VALUES (8 , 'E20KW' , 1 , 0 , 103, 'CAR' , 2);
INSERT INTO PARKINGSLOT VALUES (9 , 'E50KW' , 1 , 0 , 104, 'CAR' , 2);
INSERT INTO PARKINGSLOT VALUES (10 , 'E50KW' , 1 , 0 , 105, 'CAR' , 2);
INSERT INTO PARKINGSLOT VALUES (11 , 'E50KW' , 1 , 0 , 106, 'CAR' , 2);
--BILL
INSERT INTO BILL VALUES ( 6 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 7 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 8 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 9 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 10 , 0 , 0 , 'EUR' , 1);
INSERT INTO BILL VALUES ( 11 , 0 , 0 , 'EUR' , 1);

